name: Update Manifest JSON

on:
  push:
    branches:
      - main  # Ganti dengan branch utama repository Anda jika berbeda

jobs:
  update-manifest:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2. Jalankan script untuk membuat manifest.json
    - name: Generate Manifest
      run: |
        echo "[" > manifest.json

        # Mencari direktori dan menambahkan informasi
        find . -type d -not -path './.github*' -exec bash -c '
          folder_path="{}"
          last_update=$(stat -c %Y "$folder_path")  # Timestamp update terakhir
          echo "{\"path\": \"$folder_path\", \"name\": \"$(basename {})\", \"type\": \"dir\", \"last_update\": \"$last_update\", \"files\": [" >> manifest.json
          
          # Mencari file dalam direktori tersebut
          find "$folder_path" -maxdepth 1 -type f -exec bash -c '
            file_path="{}"
            file_name=$(basename "$file_path")
            file_type=$(file --mime-type -b "$file_path" | cut -d/ -f2)
            file_size=$(stat -c %s "$file_path")
            last_updated=$(stat -c %Y "$file_path")
            url="https://raw.githubusercontent.com/${{ github.repository }}/main/$(realpath --relative-to=. "$file_path")"
            echo "{\"path\": \"$file_path\", \"name\": \"$file_name\", \"type\": \"file\", \"format\": \"$file_type\", \"url\": \"$url\", \"size\": \"$file_size\", \"last_updated\": \"$last_updated\"}," >> manifest.json
          ' \;
          sed -i '$ s/,$//' manifest.json  # Hapus koma terakhir
          echo "]}," >> manifest.json
        ' \;

        # Menghapus koma terakhir dari file JSON jika ada
        sed -i '$ s/,$//' manifest.json
        echo "]" >> manifest.json

    # 3. Commit dan push manifest.json ke repository
    - name: Commit and Push Manifest
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add manifest.json
        git commit -m "Update manifest.json"
        git push
