name: Generate Folder Structure

on:
  push:
    branches:
      - main  # Trigger saat ada perubahan di branch utama
  pull_request:
    branches:
      - main  # Trigger saat ada PR di branch utama

jobs:
  generate_json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate folder structure JSON
      run: |
        # Script untuk menghasilkan struktur folder
        declare -A folder_structure
        
        # Iterate semua file di dalam repo
        for file in $(find . -type f); do
          folder=$(dirname "$file")
          filename=$(basename "$file")
          size=$(stat -c %s "$file")
          updated_at=$(git log -1 --format=%cd -- $file)
          download_url="https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/main/$file"
          
          # Format file data
          file_data="{\"name\": \"$filename\", \"type\": \"file\", \"size\": \"$size\", \"download_url\": \"$download_url\", \"updated_at\": \"$updated_at\"}"

          # Jika folder belum ada dalam struktur, buat entri untuk folder tersebut
          if [[ ! ${folder_structure[$folder]} ]]; then
            folder_structure[$folder]="[]"
          fi

          # Tambahkan file ke dalam folder yang sesuai
          folder_structure[$folder]=$(echo ${folder_structure[$folder]} | jq ". + [$file_data]")
        done

        # Buat file JSON akhir
        echo "[" > file-structure.json
        for folder in "${!folder_structure[@]}"; do
          echo "{\"id\": \"$folder\", \"name\": \"$folder\", \"type\": \"folder\", \"children\": ${folder_structure[$folder]}}" >> file-structure.json
        done
        echo "]" >> file-structure.json

    - name: Commit and push file structure
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add file-structure.json
        git commit -m "Update file structure JSON"
        git push
