name: Update Manifest JSON

on:
  push:
    branches:
      - main  #  branch utama repository 

jobs:
  update-manifest:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

    # 2. Jalankan script untuk membuat manifest.json
      - name: Generate Manifest
        run: |
          echo "[" > manifest.json

          # Mencari file di direktori utama dan menambahkan informasi
          find . -type f -not -path './.git/*' -not -path './.github/*' -exec bash -c '
            file_path="{}"
            # Pastikan file tidak kosong dan valid
            if [ -s "$file_path" ]; then
              file_name=$(basename "$file_path")
              file_size=$(stat -c %s "$file_path")
              last_updated=$(stat -c %Y "$file_path")
              url="https://raw.githubusercontent.com/${{ github.repository }}/main/$(realpath --relative-to=. "$file_path")"
              echo "{\"name\": \"$file_name\", \"type\": \"file\", \"size\": \"$file_size\", \"download_url\": \"$url\", \"updated_at\": \"$(date -u -d @$last_updated +"%Y-%m-%dT%H:%M:%SZ")\"}," >> manifest.json
            fi
          ' \;

          # Mencari direktori yang valid dan menambahkan informasi
          find . -type d -not -path './.git/*' -not -path './.github/*' -exec bash -c '
            folder_path="{}"
            # Pastikan folder berisi file dan bukan folder .git
            if [ "$(find "$folder_path" -maxdepth 1 -type f -not -path "$folder_path/.git/*")" ]; then
              last_update=$(stat -c %Y "$folder_path")  # Timestamp update terakhir
              echo "{\"name\": \"$(basename {})\", \"type\": \"dir\", \"size\": null, \"updated_at\": \"$(date -u -d @$last_update +"%Y-%m-%dT%H:%M:%SZ")\", \"files\": [" >> manifest.json

              # Mencari file di dalam folder dan menambahkannya
              find "$folder_path" -maxdepth 1 -type f -not -path "$folder_path/.git/*" -exec bash -c "
                file_path='{}'
                if [ -s \"\$file_path\" ]; then
                  file_name=\$(basename \"\$file_path\")
                  file_size=\$(stat -c %s \"\$file_path\")
                  last_updated=\$(stat -c %Y \"\$file_path\")
                  url=\"https://raw.githubusercontent.com/\${{ github.repository }}/main/\$(realpath --relative-to=. \"\$file_path\")\"
                  echo \"{\"name\": \"\$file_name\", \"type\": \"file\", \"size\": \"\$file_size\", \"download_url\": \"\$url\", \"updated_at\": \"\$(date -u -d @$last_updated +"%Y-%m-%dT%H:%M:%SZ")\"},\" >> manifest.json
                fi
              " \;

              sed -i '$ s/,$//' manifest.json  # Hapus koma terakhir di dalam array "files"
              echo "]}, " >> manifest.json
            fi
          ' \;

          # Menghapus koma terakhir dari file JSON jika ada
          sed -i '$ s/,$//' manifest.json
          echo "]" >> manifest.json

    # 3. Commit dan push manifest.json ke repository
      - name: Commit and Push Manifest
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add manifest.json
          git commit -m "Update manifest.json"
          git push
