name: Generate Folder Structure

on:
  push:
    branches:
      - main  # Trigger saat ada perubahan di branch utama
  pull_request:
    branches:
      - main  # Trigger saat ada PR di branch utama

jobs:
  generate_json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate folder structure JSON
      run: |
        # Install jq jika belum ada
        sudo apt-get install jq

        declare -A folder_structure

        # Iterate semua file di dalam repo
        while IFS= read -r file; do
          folder=$(dirname "$file")
          filename=$(basename "$file")

          # Abaikan folder .git, git log dan file sampel yang tidak diinginkan
          if [[ "$file" == *".git"* || "$file" == *"git-log"* || "$file" == *"sample"* ]]; then
            continue
          fi

          # Hapus './' pada path
          folder=${folder#./}
          filename=${filename#./}
          
          # Dapatkan ukuran file dan waktu update terakhir
          size=$(stat -c %s "$file")
          updated_at=$(git log -1 --format=%cd -- "$file")
          download_url="https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/main/$file"
          
          # Format data file
          file_data="{\"name\": \"$filename\", \"type\": \"file\", \"size\": \"$size\", \"download_url\": \"$download_url\", \"updated_at\": \"$updated_at\"}"

          # Jika folder belum ada dalam struktur, buat entri untuk folder tersebut
          if [[ ! ${folder_structure[$folder]} ]]; then
            folder_structure[$folder]="[]"
          fi

          # Tambahkan file ke dalam folder yang sesuai
          folder_structure[$folder]=$(echo ${folder_structure[$folder]} | jq ". + [$file_data]")
        done < <(find . -type f)

        # Buat file JSON akhir
        echo "[" > file-structure.json
        for folder in "${!folder_structure[@]}"; do
          # Hanya masukkan folder yang tidak kosong
          if [[ ${folder_structure[$folder]} != "[]" ]]; then
            echo "{\"id\": \"$folder\", \"name\": \"$folder\", \"type\": \"folder\", \"children\": ${folder_structure[$folder]}}" >> file-structure.json
          fi
        done
        echo "]" >> file-structure.json

    - name: Commit and push file structure
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add file-structure.json
        git commit -m "Update file structure JSON"
        git push
